workflows:
  windows-admin-panel:
    name: Uber Admin Panel Windows Build
    max_build_duration: 60
    instance_type: windows_x2
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
          include: true
    scripts:
      - name: Configure Windows Desktop
        script: |
          flutter config --enable-windows-desktop

      - name: Build Windows App
        script: |
          cd uber_admin_panel
          flutter pub get
          flutter build windows --release --no-tree-shake-icons

    artifacts:
      # This recursive pattern (**/) tells Codemagic to search 
      # every single folder in the repo for these files.
      - "**/build/windows/x64/runner/Release/*.exe"
      - "**/build/windows/x64/runner/Release/*.dll"
      - "**/build/windows/x64/runner/Release/data/**"
